topic2
yusuke716-create/Basic-Python pull request #2
Opened 2022-12-04 06:56 UTC by yusuke716-create

2022-12-08 12:40 UTC, wataru-dot commented on AOJ/02/02_C.py
> +if a <= b <= c:
ここはsortを使えばもっと短く書けます。

2022-12-09 12:35 UTC, takeshun256 requested changes
実装は大丈夫です！レビュー内容の修正をお願いします。

2022-12-09 12:35 UTC, takeshun256 commented on AOJ/03/03_A.py
> +    i = i + 1
🟢代入演算子を使うことで、より簡単に書けます。`while` 文では、`+=`による更新をよく使用しますね。
```suggestion
    i += 1
```

2022-12-09 12:35 UTC, takeshun256 commented on AOJ/03/03_B.py
> +    i = i + 1
🟢03_Aと同様に、代入演算子で書いてみてください。

2022-12-09 12:35 UTC, takeshun256 commented on AOJ/03/03_D.py
> +        x = x + 1
🟢03_Aと同様に、代入演算子で書いてみてください。

2022-12-13 12:06 UTC, takeshun256 approved these changes
修正をありがとうございます！
LGTM！

2023-01-31 04:53 UTC, merged